[build]
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/reconcile"
  to = "/.netlify/functions/api/reconcile"
  status = 200

[[redirects]]
  from = "/suggest"
  to = "/.netlify/functions/api/suggest"
  status = 200

[[redirects]]
  from = "/preview/*"
  to = "/.netlify/functions/api/preview/:splat"
  status = 200

[[redirects]]
  from = "/extend"
  to = "/.netlify/functions/api/extend"
  status = 200

[[redirects]]
  from = "/metadata"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/docs"
  to = "/.netlify/functions/api/docs"
  status = 200

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/api/health"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions.api]
  timeout = 30
