[build]
  command = "npm run build" # or any build command you have
  functions = "netlify/functions" # This is where Netlify will look for your functions

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express", "serverless-http"]

# Redirect all requests to the single Express function
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200
  force = true