[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/metadata"
  status = 200
  force = true

[[redirects]]
  from = "/reconcile"
  to = "/.netlify/functions/reconcile"
  status = 200
  force = true

[[redirects]]
  from = "/suggest/entity"
  to = "/.netlify/functions/suggest-entity"
  status = 200
  force = true

[[redirects]]
  from = "/suggest/type"
  to = "/.netlify/functions/suggest-type"
  status = 200
  force = true

[[redirects]]
  from = "/suggest/property"
  to = "/.netlify/functions/suggest-property"
  status = 200
  force = true

[[redirects]]
  from = "/preview"
  to = "/.netlify/functions/preview"
  status = 200
  force = true

[[redirects]]
  from = "/extend/propose"
  to = "/.netlify/functions/extend-propose"
  status = 200
  force = true

[[redirects]]
  from = "/extend"
  to = "/.netlify/functions/extend"
  status = 200
  force = true

[[redirects]]
  from = "/stream-chunk"
  to = "/.netlify/functions/stream-chunk"
  status = 200
  force = true



