[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/metadata"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200
  force = true